let a = { k: 1 };
let b = { K: 1 };
console.log(a, b, a === b);
a.k = 7;
b = a;
console.log(a, b, a === b);
a.k = 2;
console.log(a, b, a === b);
let c = b;
console.log(a, b, c, a === c);
a.k = 9;
console.log(a, b, c, a === c);
